/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bhaavan.assignment;

import com.google.common.base.Charsets;
import com.google.common.io.Resources;

import java.io.IOException;
import java.nio.charset.Charset;
import java.util.Scanner;

public class App {
    private final String SPLASH_ART_FILE = "SplashArt.txt";

    private String readResource(final String fileName, Charset charset) throws IOException {
        return Resources.toString(Resources.getResource(fileName), charset);
    }

    public String getGreeting() {
        String fixture = new String();
        try {
            fixture = readResource(SPLASH_ART_FILE, Charsets.UTF_8);
        } catch (IOException io_ex) {
            // TODO: log error
        }
        return fixture;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Scanner input = new Scanner(System.in);
        System.out.println("Enter the number of games to be played:");
        int number_of_rounds = input.nextInt();
        Arena arena = new Arena(number_of_rounds);
        arena.start();
    }
}
