/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bhaavan.assignment;

import java.io.*;
import java.util.InputMismatchException;
import java.util.Scanner;

public class App {
    private final String SPLASH_ART_FILE = "/SplashArt.txt";

    public String getGreeting() {
        String fixture = new String();
        try {
            fixture = readResource(SPLASH_ART_FILE);
        } catch (IOException io_ex) {
            System.out.println(io_ex);
            System.out.println("Couldn't fetch all resources. Proceeding anyway.");
        }
        return fixture;
    }

    private String readResource(final String fileName) throws IOException {
        InputStream in = getClass().getResourceAsStream(fileName);
        BufferedReader reader = new BufferedReader(new InputStreamReader(in));
        String output = "";
        String line = null;
        while ((line = reader.readLine()) != null) {
            output = output + '\n' + line;
        }
        return output;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Scanner input = new Scanner(System.in);
        System.out.println("Enter the number of games to be played:");
        int number_of_rounds = -1;
        try {
            number_of_rounds = input.nextInt();
        } catch (InputMismatchException e) {
            System.out.println("You entered invalid data.");
        }
        Arena arena = new Arena(number_of_rounds);
        arena.start();
    }
}
