/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void testAppHasASplashScreen() {
        App classUnderTest = new App();
        assertFalse("app should have a non null greeting", classUnderTest.getGreeting().isEmpty());
    }
}
