/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project;

import org.junit.Test;

import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

public class GameTest {
    @Test public void testDefaultsOnNegativeRounds() {
        Game classUnderTest = new Game(-1);
        assertTrue("game defaults to correct rounds on negative rounds", classUnderTest.num_rounds > 0);
    }

    @Test public void testDefaultsOnLargeRounds() {
        int large_number = 100000000;
        Game classUnderTest = new Game(large_number);
        assertTrue("game defaults to correct rounds on unreasonable number of rounds", classUnderTest.num_rounds < large_number);
    }

    @Test public void testInitializesCorrectRound() {
        int rounds = 50;
        Game classUnderTest = new Game(rounds);
        assertTrue("game defaults to correct rounds on unreasonable number of rounds", classUnderTest.num_rounds == rounds);
    }
}
