/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bhaavan.assignment;

import org.junit.Test;

import static org.junit.Assert.assertTrue;

public class ArenaTest {
    @Test public void testDefaultsOnNegativeRounds() {
        Arena classUnderTest = new Arena(-1);
        assertTrue("game defaults to correct rounds on negative rounds", classUnderTest.getNum_rounds() > 0);
    }

    @Test public void testDefaultsOnLargeRounds() {
        int large_number = 100000000;
        Arena classUnderTest = new Arena(large_number);
        assertTrue("game defaults to correct rounds on unreasonable number of rounds", classUnderTest.getNum_rounds() < large_number);
    }

    @Test public void testInitializesCorrectRound() {
        int rounds = 50;
        Arena classUnderTest = new Arena(rounds);
        assertTrue("game defaults to correct rounds on unreasonable number of rounds", classUnderTest.getNum_rounds() == rounds);
    }

    @Test public void testInitializesABot() {
        Arena classUnderTest = new Arena(10);
        assertTrue("game initializes a bot", classUnderTest.getPlayers().get(1).player_type == PlayerType.BOT);
    }

    @Test public void testInitializesAHuman() {
        Arena classUnderTest = new Arena(10);
        assertTrue("game initializes a bot", classUnderTest.getPlayers().get(0).player_type == PlayerType.HUMAN);
    }
}
