/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bhaavan.assignment;

import org.junit.Test;

import java.util.ArrayList;

import static org.junit.Assert.assertTrue;

public class ScorecardTest {
    @Test public void testScorecardInitializesCorrectly() {
        ArrayList<Player> players = new ArrayList<Player>();
        players.add(new Player(true));
        Scorecard classUnderTest = new Scorecard(players);
        assertTrue("result contains one player", classUnderTest.results.size() == 1);
        assertTrue("result contains correct start value", classUnderTest.results.containsValue(0));
    }

    @Test public void testRegistersVictory() {
        ArrayList<Player> players = new ArrayList<Player>();
        Player player = new Player(true);
        players.add(player);
        Scorecard classUnderTest = new Scorecard(players);
        classUnderTest.registerVictory(player);
        assertTrue("result correctly increases value", classUnderTest.results.containsValue(1));
    }

    @Test(expected = NullPointerException.class) public void testRegistersVictoryFailsUnknown() {
        ArrayList<Player> players = new ArrayList<Player>();
        Player player = new Player(true);
        Player player2 = new Player(true);
        players.add(player);
        Scorecard classUnderTest = new Scorecard(players);
        classUnderTest.registerVictory(player2);
    }

}
